### ISSUE TITLE
Performance tuning guide

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#1039]
Currently our Docs list out settings for many configurations.
We need a guide detailing the effect of these settings have when considered together for a QuestDB instance.

Task:
- Clarify configs to be included
- Based on the selected configs, provide content illustrate the dependencies
- Provide examples
- Potentially need to refactor individual config documentation for clarity

**Comment by puzpuzpuz** [comment]
Leaving a brain dump of various performance related guidelines here:
* Indexes have a noticeable cost in terms of disk space and ingestion rate - we recommend starting with no indexes and adding them later, only if they appear to improve query performance.
* Undersized symbol columns - capacity should be same or slightly larger than the count of distinct symbol values.
* Too many cached symbol values/columns - on-heap cache enabled for symbols may occupy a significant part of the heap in those rare cases when there are a lot of values or columns. In this case, increasing JVM max heap size (`-Xmx` argument) or disabling the cache might help. - better to check the new JVM and GC metrics before taking further steps.
* High RSS value (memory consumption) on read-most loads - this one is much less likely to happen on 6.5.3 and newer versions since all queries now release most of off-heap memory once the execution finishes. The old recommendation was to disable query caches, but it has lost its topicality - we may keep this recommendation in the guide just in case. - in non-trivial cases, it's better to check the off-heap memory metrics and share them with the core team.
* High RSS value (memory consumption) on write-most loads - in case of O3 writes over high number of columns/tables, this one is very likely to be caused by `cairo.o3.column.memory.size` (2x8MB by default for each column). Consider decreasing the value in the interval of [128K, 8M] based on the number of columns you use.
* High disk read rate on a small dataset - consider increasing RAM available on the box to improve OS page cache efficiency. We recommend having at least 8GB for basic workloads and 32GB for advanced ones.
* High disk write rate combined with high write amplification (we have the metrics for that: `questdb_physically_written_rows_total` / `questdb_committed_rows_total`) - consider increasing commit lag and, optionally, max uncommitted rows setting. As the next step, check the total size of partition directories on disk and, if they're larger than a few hundred MB, consider using smaller partitions: day -> hour, month -> day, and so on.

Some common sense recommendations:
* Use connection pooling for PG Wire, but avoid configuring the pool to use too many connections - their total number should be close enough to the number of shared worker threads used by the database.
* If you use ILP, follow this guide: https://questdb.io/docs/reference/api/ilp/tcp-receiver/#capacity-planning
* Row serialization/deserialization has a cost on both client and server, so if you're fetching a large (10K+) dataset via a single query, consider using pagination, hence multiple queries instead.

The above items have no particular order and many of them may belong to the capacity planning page. So, we may decide to convert capacity planning into something bigger than it is now. I may add a few additional items later in separate messages.

**Comment by amyshwang** [comment]
Not sure if it is suitable here but @javier shared [Performance tuning in Athena](https://docs.aws.amazon.com/athena/latest/ug/performance-tuning.html), which is about writing more efficient queries. The list above touches upon it but I wonder if we could separate:

* HW setting and configuration (overlapping with capacity planning page)
* Recommended approaches when running queries
   Using @bziobrowski's idea, this may include:
- efficient time range scanning via predicates on designated timestamp
- group by via rosti
- async offload (& jit)
- indexes
- sort + limit optimization

**Comment by amyshwang** [comment]
I am trying to separate two types of "guides"

1. Capacity planning: More HW setting (server configuration) that requires overall understanding of the data: this is an addition to the existing Capacity planning page
2. Performance fine tuning page: More one-off guidance for manipulating data: this is more similar to the [Performance tuning in Athena](https://docs.aws.amazon.com/athena/latest/ug/performance-tuning.html)

Current Capacity planning has:

- [Storage and filesystem](https://questdb.io/docs/operations/capacity-planning/#storage-and-filesystem): this is more similar to 2. above
The rest are more about server/HW configurations:
- [CPU configuration](https://questdb.io/docs/operations/capacity-planning/#cpu-configuration)
- [Network Configuration](https://questdb.io/docs/operations/capacity-planning/#network-configuration)
- [OS configuration](https://questdb.io/docs/operations/capacity-planning/#os-configuration)

Copying @puzpuzpuz's list, Capacity planning may include:
- cached symbol values/columns (no. 3)
- High RSS value (memory consumption) on write-most loads  (no. 5)
- High disk read rate on a small dataset(no. 6)
- High disk write rate combined with high write amplification (no.7) 

Performance fine tuning guide may include:
- Existing [Storage and filesystem](https://questdb.io/docs/operations/capacity-planning/#storage-and-filesystem)
- Indexes (no. 2 in @puzpuzpuz's list and @bziobrowski mentioned it too)
- Undersized symbol columns (no. 3 in the list)
- Use connection pooling for PGWire, but avoid configuring the pool to use too many connections 
- If you use ILP, follow this guide: https://questdb.io/docs/reference/api/ilp/tcp-receiver/#capacity-planning
- Row serialization/deserialization has a cost on both client and server, so if you're fetching a large (10K+) dataset via a single query, consider using pagination, hence multiple queries instead.

**Comment by amyshwang** [comment]
1. https://questdb.io/docs/operations/capacity-planning/#storage-and-filesystem to retain the "caution note"

QuestDB officially supports EXT4 or any filesystem that supports [mmap](https://man7.org/linux/man-pages/man2/mmap.2.html).

**ZFS - can be used not not being tested.**

Users can't use NFS or a similar distributed filesystem directly with a QuestDB database.

**Comment by amyshwang** [comment]
As @ideoma suggested - once content is added, we can decide if we want to separate it into a different page. Some ideas for the page name:
- Getting most from your hardware
- Design for performance

**Comment by amyshwang** [comment]
Closing this as the majority content has been captured. Will use #1080 to progress the next step.
