### ISSUE TITLE
Bug - Dead link in search results

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb.io#1044]
When I search for Join then it shows the "ASOF JOIN" result which is presumably pointing to a QuestDB - Grafana integration guide:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/158619/191012443-5edfd662-1d2b-4eed-9f12-121ebda63386.png">

However [the link](https://questdb.io/tutorial/2020/10/19/grafana/#asof-join) returns 404: 
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/158619/191011416-496d1fdb-6a7e-4c33-8433-9ab72415b1e3.png">

When I remove the anchor from the link then https://questdb.io/tutorial/2020/10/19/grafana/ redirects me to a new place: https://questdb.io/blog/2020/10/19/grafana-tutorial/ and there I can see the ASOF Join is described: https://questdb.io/blog/2020/10/19/grafana-tutorial/#asof-join

It looks like Netlify redirect rule does not match the old path when the link contains an anchor. It should be solvable via this: https://docs.netlify.com/routing/redirects/redirect-options/#splats

**Comment by jerrinot** [comment]
Update: Perhaps my analysis is flawed. I'm getting 404 only when I click at the link right in the search result. 
When I then copy the URL (which is returning 404) and paste into a new tab, including the anchor, then the redirect rule kicks in and I'm redirected to the right place. In fact it's enough to press Ctrl-R on the 404 page and it reload correctly!  I bet there is some front-end sorcery going badly: History API / Navigation API or friends.

**Comment by argshook** [comment]
Hey, @jerrinot thanks for filling the issue!

Recently we moved pages from `/tutorial` to `/blog` and although all the
redirects were fixed, it seems the Algolia search engine didn't catch
this change.

The reason everything works when accessing the link directly is because
that way there's a redirect on the server side.

Link in Algolia search popup is outdated and since it's client side
there's no redirect.
