### ISSUE TITLE
Examples for Line protocol

### ISSUE THREAD

**Issue by Snoopy9** [questdb/questdb.io#442]
I

**Comment by bsmth** [comment]
Thanks a lot for raising the issue @Snoopy9. The example is correct, but this might be misleading because of the terminology for `tags` versus `fields`

```
measurementName,tagKey=tagValue fieldKey="fieldValue" 1465839830100400200
--------------- --------------- --------------------- -------------------
       |               |                  |                    |
  Measurement         Tags              Fields             Timestamp
```

Tags are repetitive strings that appear often across a dataset, like a location, currency, a machine ID etc. Double quotes are not required for tags. I can add a note in the docs to highlight this 👍🏻

**Comment by Snoopy9** [comment]
you are right. I have carefully read the of the line protocol description in the InfluxDB manual again. It's not obvious but text is specified differently in a key and a field. We worked a lot with text fields but didn't use any text in keys. That's why we didn't notice it.
